org: tahina
app: serverless-todo-app
service: serverless-todo-app

plugins:
  - serverless-webpack
  - serverless-iam-roles-per-function
  - serverless-plugin-tracing
  - serverless-offline
  - serverless-dotenv-plugin

# https://www.serverless.com/plugins/serverless-dotenv-plugin
useDotenv: true

provider:
  name: aws
  runtime: nodejs16.x

  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'us-east-1'}

  tracing:
    lambda: true
    apiGateway: true

  # https://github.com/neverendingqs/serverless-dotenv-plugin
  environment:
    TODOS_TABLE: ${env:TODOS_TABLE, 'tahina-todos-dev'}
    TODOS_CREATED_AT_INDEX: ${env:TODOS_CREATED_AT_INDEX, 'CreatedAtIndex'}
    ATTACHMENT_S3_BUCKET: ${env:ATTACHMENT_S3_BUCKET, 'serverless-c4-todo-images-dev'}
    SIGNED_URL_EXPIRATION: ${env:SIGNED_URL_EXPIRATION, '300'}

  logs:
    # Enable API Gateway logs
    restApi: true

  # https://www.npmjs.com/package/serverless-iam-roles-per-function
  iam:
    role:
      statements:
        - Effect: Allow
          # https://docs.aws.amazon.com/xray/latest/devguide/security_iam_id-based-policy-examples.html#xray-permissions-managedpolicies
          Action:
            - xray:PutTraceSegments
            - xray:PutTelemetryRecords
            - xray:GetSamplingRules
            - xray:GetSamplingTargets
            - xray:GetSamplingStatisticSummaries
          Resource: "*"

package:
  individually: true

custom:
  webpack:
    includeModules:
      forceExclude:
        - aws-sdk
  # https://www.serverless.com/plugins/serverless-iam-roles-per-function
  serverless-iam-roles-per-function:
    defaultInherit: true
  # https://www.serverless.com/plugins/serverless-offline
  serverless-offline:
    httpPort: 5000

functions:
  Auth:
    name: tahina-todo-auth-${sls:stage}
    handler: src/lambda/auth/auth0Authorizer.handler
    # https://www.serverless.com/blog/aws-lambda-provisioned-concurrency
    provisionedConcurrency: 5
    # https://www.serverless.com/plugins/serverless-iam-roles-per-function
    iamRoleStatementsInherit: true
    # https://www.serverless.com/plugins/serverless-plugin-tracing
    tracing: true

  GetTodos:
    name: tahina-todo-list-${sls:stage}
    handler: src/lambda/http/getTodos.handler
    events:
      - http:
          method: get
          path: todos
          cors: true
          authorizer: Auth
    # https://www.serverless.com/blog/aws-lambda-provisioned-concurrency
    provisionedConcurrency: 5
    # https://www.serverless.com/plugins/serverless-iam-roles-per-function
    iamRoleStatementsInherit: true
    # https://www.serverless.com/plugins/serverless-plugin-tracing
    tracing: true
    # https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_examples_dynamodb_specific-table.html
    iamRoleStatements:
      - Effect: Allow
        Action:
          - dynamodb:Query
        Resource: arn:aws:dynamodb:${aws:region}:*:table/${self:provider.environment.TODOS_TABLE}/index/${self:provider.environment.TODOS_CREATED_AT_INDEX}

  CreateTodo:
    name: tahina-todo-create-${sls:stage}
    handler: src/lambda/http/createTodo.handler
    events:
      - http:
          method: post
          path: todos
          cors: true
          authorizer: Auth
    # https://www.serverless.com/blog/aws-lambda-provisioned-concurrency
    provisionedConcurrency: 5
    # https://www.serverless.com/plugins/serverless-iam-roles-per-function
    iamRoleStatementsInherit: true
    # https://www.serverless.com/plugins/serverless-plugin-tracing
    tracing: true
    # https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_examples_dynamodb_specific-table.html
    iamRoleStatements:
      - Effect: Allow
        Action:
          - dynamodb:PutItem
        Resource: arn:aws:dynamodb:${aws:region}:*:table/${self:provider.environment.TODOS_TABLE}

  UpdateTodo:
    name: tahina-todo-update-${sls:stage}
    handler: src/lambda/http/updateTodo.handler
    events:
      - http:
          method: patch
          path: todos/{todoId}
          cors: true
          authorizer: Auth
    # https://www.serverless.com/blog/aws-lambda-provisioned-concurrency
    provisionedConcurrency: 5
    # https://www.serverless.com/plugins/serverless-iam-roles-per-function
    iamRoleStatementsInherit: true
    # https://www.serverless.com/plugins/serverless-plugin-tracing
    tracing: true
    # https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_examples_dynamodb_specific-table.html
    iamRoleStatements:
      - Effect: Allow
        Action:
          - dynamodb:UpdateItem
        Resource: arn:aws:dynamodb:${aws:region}:*:table/${self:provider.environment.TODOS_TABLE}

  DeleteTodo:
    name: tahina-todo-delete-${sls:stage}
    handler: src/lambda/http/deleteTodo.handler
    events:
      - http:
          method: delete
          path: todos/{todoId}
          cors: true
          authorizer: Auth
    # https://www.serverless.com/blog/aws-lambda-provisioned-concurrency
    provisionedConcurrency: 5
    # https://www.serverless.com/plugins/serverless-iam-roles-per-function
    iamRoleStatementsInherit: true
    # https://www.serverless.com/plugins/serverless-plugin-tracing
    tracing: true
    # https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_examples_dynamodb_specific-table.html
    iamRoleStatements:
      - Effect: Allow
        Action:
          - dynamodb:DeleteItem
        Resource: arn:aws:dynamodb:${aws:region}:*:table/${self:provider.environment.TODOS_TABLE}

  GenerateUploadUrl:
    name: tahina-todo-generateUploadUrl-${sls:stage}
    handler: src/lambda/http/generateUploadUrl.handler
    events:
      - http:
          method: post
          path: todos/{todoId}/attachment
          cors: true
          authorizer: Auth
    # https://www.serverless.com/blog/aws-lambda-provisioned-concurrency
    provisionedConcurrency: 5
    # https://www.serverless.com/plugins/serverless-iam-roles-per-function
    iamRoleStatementsInherit: true
    # https://www.serverless.com/plugins/serverless-plugin-tracing
    tracing: true
    iamRoleStatements:
      - Effect: Allow
        Action:
          - s3:PutObject
        Resource: "arn:aws:s3:::${self:provider.environment.ATTACHMENT_S3_BUCKET}/*"
      - Effect: Allow
        Action:
          - dynamodb:UpdateItem
          - dynamodb:GetItem
        Resource: arn:aws:dynamodb:${aws:region}:*:table/${self:provider.environment.TODOS_TABLE}

resources:
  Resources:
    GatewayResponseDefault4XX:
      Type: AWS::ApiGateway::GatewayResponse
      Properties:
        ResponseParameters:
          gatewayresponse.header.Access-Control-Allow-Origin: "'*'"
          gatewayresponse.header.Access-Control-Allow-Headers: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
          gatewayresponse.header.Access-Control-Allow-Methods: "'GET,OPTIONS,POST,PATCH,DELETE'"
        ResponseType: DEFAULT_4XX
        RestApiId:
          Ref: ApiGatewayRestApi

    TodosTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: userId
            AttributeType: S
          - AttributeName: todoId
            AttributeType: S
          - AttributeName: createdAt
            AttributeType: S
        KeySchema:
          - AttributeName: userId
            KeyType: HASH
          - AttributeName: todoId
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST
        TableName: ${self:provider.environment.TODOS_TABLE}
        LocalSecondaryIndexes:
          - IndexName: ${self:provider.environment.TODOS_CREATED_AT_INDEX}
            KeySchema:
              - AttributeName: userId
                KeyType: HASH
              - AttributeName: createdAt
                KeyType: RANGE
            Projection:
              ProjectionType: ALL # What attributes will be copied to an index

    AttachmentsBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:provider.environment.ATTACHMENT_S3_BUCKET}
        CorsConfiguration:
          CorsRules:
            -
              AllowedOrigins:
                - '*'
              AllowedHeaders:
                - '*'
              AllowedMethods:
                - GET
                - PUT
                - POST
                - DELETE
                - HEAD
              MaxAge: 3000

    BucketPolicy:
      Type: AWS::S3::BucketPolicy
      Properties:
        PolicyDocument:
          Id: MyPolicy
          Version: "2012-10-17"
          Statement:
            - Sid: PublicReadForGetBucketObjects
              Effect: Allow
              Principal: '*'
              Action: 's3:GetObject'
              Resource: 'arn:aws:s3:::${self:provider.environment.ATTACHMENT_S3_BUCKET}/*'
        Bucket: !Ref AttachmentsBucket
